#!/usr/bin/env python3
"""
Code Generation Agent

A Python script that acts as an intelligent code generation agent.
It takes user descriptions and generates appropriate Python code for modules or scripts.

Author: Generated by code_agent.py
Date: 2024
"""

import os
import re
from typing import Optional, Tuple


class CodeGenerator:
    """
    A class responsible for generating Python code based on user descriptions.
    """

    def __init__(self):
        """Initialize the code generator."""
        self.templates = {
            'module': self._generate_module_template,
            'script': self._generate_script_template,
            'fibonacci': self._generate_fibonacci_script,
            'data_processing': self._generate_data_processing_module,
            'calculator': self._generate_calculator_script,
        }

    def parse_description(self, description: str) -> Tuple[str, dict]:
        """
        Parse the user description to determine the type of code to generate.

        Args:
            description (str): User description of what to build

        Returns:
            Tuple[str, dict]: Type of code and additional parameters
        """
        description_lower = description.lower()

        # Determine code type
        if 'module' in description_lower:
            code_type = 'module'
        elif 'fibonacci' in description_lower:
            code_type = 'fibonacci'
        elif 'data processing' in description_lower or 'data' in description_lower:
            code_type = 'data_processing'
        elif 'calculator' in description_lower or 'calculate' in description_lower:
            code_type = 'calculator'
        else:
            code_type = 'script'

        # Extract additional parameters
        params = {}
        if 'fibonacci' in description_lower:
            # Look for number in description
            numbers = re.findall(r'\d+', description)  # CODE_AGENT_PARAMS_N_INT_NUMBERS — regex \d+ extracts all digit sequences from user input; first match used as sequence length
            if numbers:
                params['n'] = int(numbers[0])
            else:
                params['n'] = 10  # DEFAULT_FIBONACCI_TERMS=10 — fallback Fibonacci sequence length when no number specified in description

        return code_type, params

    def generate_code(self, description: str) -> str:
        """
        Generate Python code based on the description.

        Args:
            description (str): User description

        Returns:
            str: Generated Python code
        """
        code_type, params = self.parse_description(description)

        if code_type in self.templates:
            return self.templates[code_type](**params)
        else:
            return self._generate_generic_script(description)

    def _generate_module_template(self, **kwargs) -> str:
        """Generate a basic Python module template."""
        return '''"""
Basic Python Module

This is a basic module template that can be extended with specific functionality.

Author: Code Generation Agent
"""

class BasicModule:
    """
    A basic module class that can be extended.
    """

    def __init__(self):
        """Initialize the module."""
        self.data = {}

    def process(self, input_data):
        """
        Process input data.

        Args:
            input_data: The data to process

        Returns:
            Processed data
        """
        try:
            # Basic processing logic - extend as needed
            if isinstance(input_data, dict):
                self.data.update(input_data)
                return f"Processed {len(input_data)} items"
            elif isinstance(input_data, list):
                return [item.upper() if isinstance(item, str) else item for item in input_data]
            else:
                return str(input_data).upper()
        except Exception as e:
            raise ValueError(f"Error processing data: {e}")

    def get_data(self):
        """
        Get stored data.

        Returns:
            dict: Stored data
        """
        return self.data.copy()


def main():
    """Main function for testing the module."""
    module = BasicModule()
    test_data = {"key": "value", "number": 42}
    result = module.process(test_data)
    print(f"Result: {result}")
    print(f"Stored data: {module.get_data()}")


if __name__ == "__main__":
    main()
'''

    def _generate_script_template(self, **kwargs) -> str:
        """Generate a basic Python script template."""
        return '''#!/usr/bin/env python3
"""
Basic Python Script

This is a basic script template that can be extended with specific functionality.

Author: Code Generation Agent
"""

import sys
import argparse


def main():
    """
    Main function that handles command line arguments and execution.
    """
    parser = argparse.ArgumentParser(description="Basic Python Script")
    parser.add_argument("--input", "-i", help="Input data or file")
    parser.add_argument("--output", "-o", help="Output file")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")

    args = parser.parse_args()

    try:
        # Basic script logic - extend as needed
        if args.input:
            print(f"Processing input: {args.input}")
        else:
            print("No input provided. Use --input or -i to specify input.")

        if args.verbose:
            print("Verbose mode enabled")

        # Example processing
        result = f"Processed: {args.input or 'default'}"

        if args.output:
            with open(args.output, 'w') as f:
                f.write(result)
            print(f"Result written to {args.output}")
        else:
            print(f"Result: {result}")

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
'''

    def _generate_fibonacci_script(self, n: int = 10) -> str:
        """Generate a Fibonacci sequence calculator script."""
        return f'''#!/usr/bin/env python3
"""
Fibonacci Sequence Calculator

Calculates and displays the Fibonacci sequence up to n terms.

Author: Code Generation Agent
"""

import sys


def fibonacci_iterative(n: int) -> list:
    """
    Calculate Fibonacci sequence using iterative approach.

    Args:
        n (int): Number of terms to generate

    Returns:
        list: Fibonacci sequence

    Raises:
        ValueError: If n is negative
    """
    if n < 0:
        raise ValueError("Number of terms must be non-negative")

    if n == 0:
        return []
    elif n == 1:
        return [0]
    elif n == 2:
        return [0, 1]

    sequence = [0, 1]
    for i in range(2, n):
        sequence.append(sequence[i-1] + sequence[i-2])

    return sequence


def fibonacci_recursive(n: int) -> list:
    """
    Calculate Fibonacci sequence using recursive approach.

    Args:
        n (int): Number of terms to generate

    Returns:
        list: Fibonacci sequence

    Raises:
        ValueError: If n is negative
    """
    if n < 0:
        raise ValueError("Number of terms must be non-negative")

    def fib_helper(k):
        if k <= 0:
            return []
        elif k == 1:
            return [0]
        elif k == 2:
            return [0, 1]
        else:
            prev = fib_helper(k-1)
            return prev + [prev[-1] + prev[-2]]

    return fib_helper(n)


def main():
    """
    Main function to calculate and display Fibonacci sequence.
    """
    try:
        # Default number of terms
        default_n = {n}

        print(f"Calculating Fibonacci sequence for {{default_n}} terms...")

        # Use iterative approach for better performance
        sequence = fibonacci_iterative(default_n)

        print(f"Fibonacci sequence (first {{default_n}} terms):")
        print(sequence)

        # Calculate and display the nth term
        if sequence:
            print(f"The {{len(sequence)}}th term is: {{sequence[-1]}}")

    except ValueError as e:
        print(f"Error: {{e}}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Unexpected error: {{e}}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
'''

    def _generate_data_processing_module(self, **kwargs) -> str:
        """Generate a data processing module."""
        return '''"""
Data Processing Module

A module for processing various types of data including CSV, JSON, and text files.

Author: Code Generation Agent
"""

import json
import csv
import os
from typing import List, Dict, Any, Union


class DataProcessor:
    """
    A class for processing different types of data files.
    """

    def __init__(self):
        """Initialize the data processor."""
        self.processed_data = []

    def load_csv(self, file_path: str) -> List[Dict[str, Any]]:
        """
        Load data from a CSV file.

        Args:
            file_path (str): Path to the CSV file

        Returns:
            List[Dict[str, Any]]: Loaded data as list of dictionaries

        Raises:
            FileNotFoundError: If file doesn't exist
            ValueError: If file format is invalid
        """
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"File not found: {file_path}")

        try:
            with open(file_path, 'r', newline='', encoding='utf-8') as csvfile:
                reader = csv.DictReader(csvfile)
                data = list(reader)
                self.processed_data.extend(data)
                return data
        except Exception as e:
            raise ValueError(f"Error loading CSV file: {e}")

    def load_json(self, file_path: str) -> Union[Dict[str, Any], List[Any]]:
        """
        Load data from a JSON file.

        Args:
            file_path (str): Path to the JSON file

        Returns:
            Union[Dict[str, Any], List[Any]]: Loaded JSON data

        Raises:
            FileNotFoundError: If file doesn't exist
            ValueError: If JSON is invalid
        """
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"File not found: {file_path}")

        try:
            with open(file_path, 'r', encoding='utf-8') as jsonfile:
                data = json.load(jsonfile)
                if isinstance(data, list):
                    self.processed_data.extend(data)
                elif isinstance(data, dict):
                    self.processed_data.append(data)
                return data
        except json.JSONDecodeError as e:
            raise ValueError(f"Invalid JSON file: {e}")
        except Exception as e:
            raise ValueError(f"Error loading JSON file: {e}")

    def process_text(self, text: str) -> Dict[str, Any]:
        """
        Process plain text data.

        Args:
            text (str): Text to process

        Returns:
            Dict[str, Any]: Processed text statistics
        """
        try:
            lines = text.split('\n')
            words = text.split()
            chars = len(text)

            result = {{
                'lines': len(lines),
                'words': len(words),
                'characters': chars,
                'average_words_per_line': len(lines) / len(words) if words else 0
            }}

            self.processed_data.append(result)
            return result

        except Exception as e:
            raise ValueError(f"Error processing text: {e}")

    def get_processed_data(self) -> List[Any]:
        """
        Get all processed data.

        Returns:
            List[Any]: List of processed data items
        """
        return self.processed_data.copy()

    def save_to_json(self, data: Any, file_path: str) -> None:
        """
        Save data to a JSON file.

        Args:
            data: Data to save
            file_path (str): Output file path

        Raises:
            ValueError: If data cannot be serialized
        """
        try:
            with open(file_path, 'w', encoding='utf-8') as jsonfile:
                json.dump(data, jsonfile, indent=2, ensure_ascii=False)
        except Exception as e:
            raise ValueError(f"Error saving to JSON: {e}")


def main():
    """Main function for testing the data processing module."""
    processor = DataProcessor()

    # Test with sample text
    sample_text = "This is a sample text.\nIt has multiple lines.\nAnd several words."  # CODE_AGENT_SAMPLE_TEXT — multi-line test string with literal \n for process_text() demo
    result = processor.process_text(sample_text)
    print("Text processing result:")
    print(json.dumps(result, indent=2))

    print(f"\\nTotal processed items: {len(processor.get_processed_data())}")  # CODE_AGENT_PRINT_NEWLINE_LF — literal \n in f-string produces newline character


if __name__ == "__main__":
    main()
'''

    def _generate_calculator_script(self, **kwargs) -> str:
        """Generate a basic calculator script."""
        return '''#!/usr/bin/env python3
"""
Basic Calculator Script

A simple command-line calculator that performs basic arithmetic operations.

Author: Code Generation Agent
"""

import sys
import operator
from typing import Union


class Calculator:
    """
    A simple calculator class that performs basic arithmetic operations.
    """

    def __init__(self):
        """Initialize the calculator."""
        self.operations = {{
            '+': operator.add,
            '-': operator.sub,
            '*': operator.mul,
            '/': operator.truediv,
            '**': operator.pow,
            '%': operator.mod,
        }}

    def calculate(self, num1: Union[int, float], operator: str, num2: Union[int, float]) -> Union[int, float]:
        """
        Perform calculation with two numbers and an operator.

        Args:
            num1: First number
            operator: Arithmetic operator (+, -, *, /, **, %)
            num2: Second number

        Returns:
            Result of the calculation

        Raises:
            ValueError: If operator is invalid or division by zero
        """
        if operator not in self.operations:
            raise ValueError(f"Invalid operator: {operator}. Supported: {list(self.operations.keys())}")

        if operator == '/' and num2 == 0:
            raise ValueError("Division by zero is not allowed")

        try:
            return self.operations[operator](num1, num2)
        except Exception as e:
            raise ValueError(f"Calculation error: {e}")

    def evaluate_expression(self, expression: str) -> Union[int, float]:
        """
        Evaluate a simple arithmetic expression.

        Args:
            expression: Expression like "2 + 3" or "10 * 5"

        Returns:
            Result of the expression

        Raises:
            ValueError: If expression is invalid
        """
        try:
            # Simple expression parser for basic operations
            parts = expression.split()
            if len(parts) != 3:  # EXPRESSION_PARSER_MIN_PARTS=3 — simple space-split parser requires exactly "num op num" format (3 tokens)
                raise ValueError("Expression must be in format: number operator number")

            num1 = float(parts[0])
            op = parts[1]
            num2 = float(parts[2])

            return self.calculate(num1, op, num2)

        except ValueError as e:
            raise ValueError(f"Invalid expression: {e}")
        except Exception as e:
            raise ValueError(f"Error evaluating expression: {e}")


def main():
    """
    Main function for the calculator script.
    """
    calculator = Calculator()

    print("Basic Calculator")
    print("Supported operations: +, -, *, /, ** (power), % (modulo)")
    print("Enter expressions like '2 + 3' or 'quit' to exit")

    while True:
        try:
            user_input = input("\\nEnter expression: ").strip()

            if user_input.lower() in ['quit', 'exit', 'q']:
                print("Goodbye!")
                break

            if not user_input:
                continue

            result = calculator.evaluate_expression(user_input)
            print(f"Result: {result}")

        except ValueError as e:
            print(f"Error: {e}")
        except KeyboardInterrupt:
            print("\\nGoodbye!")
            break
        except Exception as e:
            print(f"Unexpected error: {e}")


if __name__ == "__main__":
    main()
'''

    def _generate_generic_script(self, description: str) -> str:
        """Generate a generic script based on description."""
        return f'''#!/usr/bin/env python3
"""
Generic Script

Generated based on description: {description}

Author: Code Generation Agent
"""

import sys


def main():
    """
    Main function - customize based on requirements.
    """
    try:
        print(f"Script generated for: {description}")
        print("Please customize this script according to your needs.")

        # Add your custom logic here

    except Exception as e:
        print(f"Error: {{e}}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
'''


def main():
    """
    Main function for the code generation agent.
    """
    print("Welcome to the Code Generation Agent!")
    print("Describe what you want to build, and I'll generate the Python code for you.")
    print("Type 'quit' or 'exit' to stop.")

    generator = CodeGenerator()

    while True:
        try:
            user_input = input("\\nWhat would you like to build? ").strip()

            if user_input.lower() in ['quit', 'exit', 'q']:
                print("Thank you for using the Code Generation Agent!")
                break

            if not user_input:
                continue

            # Generate code
            generated_code = generator.generate_code(user_input)

            print("\\n" + "="*50)
            print("GENERATED CODE:")
            print("="*50)
            print(generated_code)
            print("="*50)

            # Ask if user wants to save to file
            save_choice = input("\\nSave this code to a file? (y/n): ").strip().lower()

            if save_choice in ['y', 'yes']:
                filename = input("Enter filename (e.g., my_script.py): ").strip()
                if not filename:
                    filename = "generated_code.py"

                # Ensure .py extension
                if not filename.endswith('.py'):
                    filename += '.py'

                try:
                    with open(filename, 'w', encoding='utf-8') as f:
                        f.write(generated_code)
                    print(f"Code saved to {filename}")
                except Exception as e:
                    print(f"Error saving file: {e}")

        except KeyboardInterrupt:
            print("\\n\\nThank you for using the Code Generation Agent!")
            break
        except Exception as e:
            print(f"Unexpected error: {e}")


if __name__ == "__main__":
    main()
